name: pixart
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.9.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.29.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - brotlipy==0.7.0
      - bs4==0.0.2
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - clean-fid==0.1.35
      - click==8.1.7
      - clip-by-openai==1.1
      - cmake==3.29.2
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.18.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - diffusers==0.27.2
      - dill==0.3.8
      - dnspython==2.2.1
      - dpcpp-cpp-rt==2024.1.0
      - einops==0.7.0
      - exceptiongroup==1.0.4
      - executing==2.0.1
      - expecttest==0.1.4
      - fairscale==0.4.13
      - fastapi==0.110.1
      - ffmpy==0.3.2
      - filelock==3.13.3
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - future==0.18.2
      - gradio==4.1.1
      - gradio-client==0.7.0
      - grpcio==1.62.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-cli==0.1
      - huggingface-hub==0.23.0
      - humanfriendly==10.0
      - hypothesis==6.61.0
      - idna==3.6
      - image-reward==1.5
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - intel-cmplr-lib-rt==2024.1.0
      - intel-cmplr-lic-rt==2024.1.0
      - intel-opencl-rt==2024.1.0
      - intel-openmp==2024.1.0
      - ipdb==0.13.13
      - ipykernel==6.29.4
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - lit==18.1.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mkl==2024.1.0
      - mkl-fft==1.3.1
      - mkl-service==2.4.0
      - mmcv==1.7.0
      - mpmath==1.2.1
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.22.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai-clip==1.0.1
      - opencv-python==4.9.0.80
      - optimum==1.18.0
      - orjson==3.10.0
      - outcome==1.3.0.post0
      - packaging==23.2
      - pandas==2.2.1
      - parso==0.8.4
      - peft==0.6.2
      - pexpect==4.9.0
      - pillow==9.3.0
      - platformdirs==4.2.0
      - plotly==5.20.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-etcd==0.4.5
      - python-multipart==0.0.9
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pyyaml==6.0
      - pyzmq==25.1.2
      - referencing==0.34.0
      - regex==2023.10.3
      - requests==2.31.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - scipy==1.13.0
      - selenium==4.16.0
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.37.2
      - sympy==1.11.1
      - tbb==2021.12.0
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - timm==0.6.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchelastic==0.2.2
      - torchmetrics==1.3.2
      - torchtext==0.14.1
      - torchvision==0.16.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.27.4
      - trio==0.23.2
      - trio-websocket==0.11.1
      - triton==2.1.0
      - typer==0.12.2
      - types-dataclasses==0.6.6
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.0.2
      - wsproto==1.2.0
      - xformers==0.0.23
      - xxhash==3.4.1
      - yapf==0.40.1
      - yarl==1.9.4
      - zipp==3.18.1