part_fp_list: "./t2v/configs/quant/remain_fp.txt"
smooth_quant_list: ""
model:
    model_id: "opensora"
    model_type: 'opensora'  # ['sd','sdxl']
conditional: True
mixed_precision: [4,6,8]
# timestep_wise: True
calib_data:
    path: "your path of calib data"
    n_steps: 10    # calib_data_sample_steps = total setps // n_steps
    batch_size: 4  # used for quant param initialization
    n_samples: 10
    #iters_w: 20000
    #iters_a: 5000
quant:
    weight:
        quantizer:
            n_bits: 8
            channel_wise: True
            per_group: "channel"
            channel_dim: 0
            scale_method: 'min_max'
            # round_mode: 'learned_hard_sigmoid'
            round_mode: 'nearest'
    activation:
        quantizer:
            n_bits: 8
            channel_wise: False
            per_group: "token"
            scale_method: 'min_max'
            round_mode: 'nearest_ste'
            running_stat: False
            dynamic: True
            sym: False
            n_spatial_token: 1024  # for 16x512x512
            n_temporal_token: 16
            n_prompt: 120
            softmax: 
                # n_bits: 16
                # channel_wise: False
                # scale_method: 'min_max'
                # round_mode: 'nearest'
                # always_zero: True
            smooth_quant: # les: it is only for convenience to put smooth quant configs under act quantizer
                enable: False
                channel_wise_scale_type: momentum_act_max
                momentum: 0.95
                alpha: 0.6250

    grad_checkpoint: False
resume_with_w_quantized:
    path: None
